### ISSUE TITLE
CI: Fails on JDK 11

### ISSUE THREAD

**Issue by olleolleolle** [torquebox/jruby-maven-plugins#108]
This Issue is a sign-post that the Travis job fails with a `java.lang.RuntimeException: unsupported Java version: 11`

https://travis-ci.org/github/torquebox/jruby-maven-plugins/builds/708197639#L2208

```
Downloaded from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/org/apache/maven/maven-error-diagnostics/2.2.1/maven-error-diagnostics-2.2.1.jar (13 kB at 57 kB/s)

Exception in thread "main" java.lang.ExceptionInInitializerError

	at org.jruby.Main.<init>(Main.java:103)

	at org.jruby.Main.main(Main.java:197)

Caused by: java.lang.RuntimeException: unsupported Java version: 11

	at org.jruby.RubyInstanceConfig.initGlobalJavaVersion(RubyInstanceConfig.java:1674)

	at org.jruby.RubyInstanceConfig.<clinit>(RubyInstanceConfig.java:1387)

	... 2 more

[ERROR] Command execution failed.

org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```

**Comment by deivid-rodriguez** [comment]
CI is now green on Java 11, this can be closed!

**Comment by olleolleolle** [comment]
Thanks, @deivid-rodriguez!
